# Generated by Django 2.1.7 on 2019-03-05 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to=settings.FILER_IMAGE_MODEL, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.CategoryLevelTwo'),
        ),
    ]
