# Generated by Django 2.1.7 on 2019-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylevelone',
            name='category',
        ),
        migrations.AlterField(
            model_name='categorylevelone',
            name='name',
            field=models.CharField(max_length=10, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='categorylevelone',
            name='title',
            field=models.CharField(max_length=10, verbose_name='中文名稱'),
        ),
        migrations.AlterField(
            model_name='categorylevelthree',
            name='name',
            field=models.CharField(max_length=10, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='categorylevelthree',
            name='title',
            field=models.CharField(max_length=10, verbose_name='中文名稱'),
        ),
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='name',
            field=models.CharField(max_length=10, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='title',
            field=models.CharField(max_length=10, verbose_name='中文名稱'),
        ),
    ]
