# Generated by Django 2.1.7 on 2019-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190305_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='key',
            field=models.IntegerField(db_index=True, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3, verbose_name='利率'),
        ),
        migrations.AlterUniqueTogether(
            name='profit',
            unique_together={('key',)},
        ),
    ]
