# Generated by Django 2.1.7 on 2019-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190410_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myosupplier',
            name='address',
            field=models.CharField(max_length=50, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='tax_address',
            field=models.CharField(max_length=50, verbose_name='發票地址'),
        ),
    ]
