# Generated by Django 2.1.7 on 2019-03-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190305_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profit',
            unique_together={('key', 'container')},
        ),
    ]
