# Generated by Django 2.1.7 on 2019-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190410_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myosupplier',
            name='account_contact_email',
            field=models.CharField(blank=True, max_length=20, verbose_name='帳戶郵件'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='account_contact_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='帳戶聯絡人'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='account_contact_tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='帳戶聯絡人電話'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='account_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='戶名'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='bank',
            field=models.CharField(blank=True, max_length=20, verbose_name='銀行'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='匯款帳號'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='branch_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='分行代碼'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='branch_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='分行名稱'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='company_tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='contact_sales',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡人'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='contact_sales_mob',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡人手機'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='contact_sales_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡人電話'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='description',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='公司傳真'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='3+2郵遞區號'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='tax_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='發票地址'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='公司電話'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='transit_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='銀行代碼'),
        ),
        migrations.AlterField(
            model_name='myosupplier',
            name='website',
            field=models.URLField(blank=True, max_length=250, verbose_name='廠商網頁'),
        ),
    ]
