# Generated by Django 2.1.7 on 2019-03-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190302_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylevelthree',
            options={'verbose_name_plural': '建立第三層分類名稱'},
        ),
        migrations.AlterUniqueTogether(
            name='categorylevelthree',
            unique_together={('name',)},
        ),
    ]
