# Generated by Django 2.1.7 on 2019-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190410_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myosupplier',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='廠商名稱'),
        ),
    ]
