# Generated by Django 2.1.7 on 2019-03-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190302_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit',
            options={'verbose_name_plural': '利潤分配表'},
        ),
    ]
