# Generated by Django 2.1.7 on 2019-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190410_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallevelthree',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='建檔日期'),
        ),
        migrations.AddField(
            model_name='materiallevelthree',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='資料更新日期'),
        ),
        migrations.AlterField(
            model_name='materiallevelthree',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品說明'),
        ),
        migrations.AlterField(
            model_name='materiallevelthree',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='materiallevelthree',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='中文名稱'),
        ),
    ]
