# Generated by Django 2.1.7 on 2019-04-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20190410_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiallevelthree',
            options={'verbose_name_plural': '建立原料第三層分類名稱'},
        ),
        migrations.AddField(
            model_name='materiallevelone',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='建檔日期'),
        ),
        migrations.AddField(
            model_name='materiallevelone',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='資料更新日期'),
        ),
        migrations.AddField(
            model_name='materialleveltwo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='建檔日期'),
        ),
        migrations.AddField(
            model_name='materialleveltwo',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='資料更新日期'),
        ),
        migrations.AlterField(
            model_name='materiallevelone',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品說明'),
        ),
        migrations.AlterField(
            model_name='materiallevelthree',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.MaterialLevelTwo'),
        ),
        migrations.AlterField(
            model_name='materiallevelthree',
            name='name',
            field=models.CharField(max_length=50, verbose_name='原料名稱'),
        ),
        migrations.AlterField(
            model_name='materiallevelthree',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='輔助說明'),
        ),
        migrations.AlterField(
            model_name='materialleveltwo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.MaterialLevelOne'),
        ),
        migrations.AlterField(
            model_name='materialleveltwo',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品說明'),
        ),
    ]
